name: Hello World

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  hello_world:
    runs-on: self-hosted

    steps:
      - name: Hello World
        run: |
          echo "Hello World!"
        shell: cmd
