name: R Hello World

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  r_hello_world:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: R Hello World
        run: run_hello_world.cmd
