name: Update Datawarehouse

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  update_datawarehouse:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: R Hello World
        run: |
          run_update_datawarehouse.cmd
        shell: cmd
